### ISSUE TITLE
Material about library for Android

### ISSUE THREAD

**Issue by janheinrichmerker** [HeinrichReimer/open-source-library-request-manager#3]
- [x] I have verified this request matches _all [rules](https://github.com/HeinrichReimer/open-source-library-request-manager#rules)_.
#### Description:

The library should basically make it easy to create an about screen like we can see in _Phonograph_. To achieve this we could possibly nest `RecyclerView`s. One for the list of "cards" plus the header card featuring the app icon and basic information in a custom layout, and nested in this `RecyclerView` there should be `RexyclerView`s for each card that hold custom actions/information in form of a list.

Strong emphasis should be to design it 100% according to material guidelines.

One idea is to maybe implement this on iOS too.
#### Platform(s) / language(s):
- Android (Java/Kotlin)
- iOS (C#/Swift; optionally)
#### Attachments:

(Links, mockups, screenshots, API specs)

https://play.google.com/store/apps/details?id=com.kabouzeid.gramophone

![](http://i. imgur.com/yUKgrUq.png)
![](http://i.imgur.com/uDnH0BW.png)
![](http://i.imgur.com/NKQP5XJ.png)

**Comment by daniel-stoneuk** [comment]
This looks awesome. I might work on something like this, just need to get my head around managing an open source library.

**Comment by daniel-stoneuk** [comment]
Been working on creating this today, probably 60% of the way. I'm using your libraries @HeinrichReimer as a guideline so the API should be pretty intuitive. Hope no one has done it yet!

**Comment by daniel-stoneuk** [comment]
Here it is: https://github.com/daniel-stoneuk/material-about-library

Mark this issue as closed?

**Comment by janheinrichmerker** [comment]
Coool!!!
